### ISSUE TITLE
`<Input>` should allow `null` for `@value`

### ISSUE THREAD

**Issue by wagenet** [typed-ember/glint#103]
```
app/components/setup-manual.hbs:9:10 - error TS2322: Type 'string | null' is not assignable to type 'string | undefined'.
  Type 'null' is not assignable to type 'string | undefined'.

9         @value={{this.appName}}
```

```hbs
      <Input
        @value={{this.appName}}
      />
```

**Comment by dfreeman** [comment]
Is it documented anywhere that `<Input>` accepts `null` as a value?

**Comment by wagenet** [comment]
It seems to work, but maybe it's bad that we're doing it :)

**Comment by wagenet** [comment]
Docs don't say anything about allowed values at all except to imply that at least a string is acceptable. https://api.emberjs.com/ember/release/classes/Ember.Templates.components/methods/Input?anchor=Input

**Comment by wagenet** [comment]
In theory `@value` can take any value and will just do a string coercion on it. However, I see the value in limiting it to string since `@value` is two-way and any returned value will be a string.
