### ISSUE TITLE
Support positional params on Ember Components

### ISSUE THREAD

**Issue by wagenet** [typed-ember/glint#105]
```
{{#async-await this.promise as |value|}}
    <SynchronousComponent @value={{value}} />
  {{else}}
    <LoadingSpinner />
  {{/async-await}}
```

https://github.com/tildeio/ember-async-await-helper/blob/master/addon/components/async-await.js

**Comment by bakerac4** [comment]
I ran into this as well while trying to type `animated-if` from `ember-animated`.

**Comment by wagenet** [comment]
@bakerac4 it’s not a smooth, but positional params just back a named param, so you can use the actual names version as well.
