### ISSUE TITLE
[Unverified] Set function as HTML attribute

### ISSUE THREAD

**Issue by wagenet** [typed-ember/glint#107]
I need to check our code to verify that this actually behaves as expected.

```
app/components/git-hub/avatar.hbs:11:15 - error TS2345: Argument of type '() => void' is not assignable to parameter of type 'string | number | boolean | void | AcceptsBlocks<{}> | null'.
  Type '() => void' is not assignable to type 'AcceptsBlocks<{}>'.
    Type 'void' is not assignable to type '{ [Blocks]: true; }'.

11       onerror={{this.imgDidError}}
```

```hbs
    <img
      class="avatar-image"
      src={{this.avatarURL}}
      alt={{this.altText}}
      onerror={{this.imgDidError}}
    >
```

**Comment by dfreeman** [comment]
That does work at runtime, but our current leaning is to nudge people toward using the Octane-idiomatic `{{on}}` modifier instead.

It's been suggested (see [#3 under Alternatives in the strict mode RFC](https://github.com/emberjs/rfcs/blob/master/text/0496-handlebars-strict-mode.md) that the intent is ultimately to move to "attributes mean attributes" semantics down the line.

**Comment by wagenet** [comment]
I had thought image was a special case, but I guess we should try `{{on "error" this.imgDidError}}`.

**Comment by dfreeman** [comment]
I just tried it out and got an error event as expected, so I think that's probably a viable option.

That said, people are of course going to run into this, so this definitely makes the "things we should try and have a friendly error message for" list.
