### ISSUE TITLE
`if` type narrowing is lost inside further nested blocks

### ISSUE THREAD

**Issue by wagenet** [typed-ember/glint#143]
<img width="1187" alt="image" src="https://user-images.githubusercontent.com/9835/114084355-f0db7d80-9864-11eb-890c-dd96a3aafb73.png">

**Comment by dfreeman** [comment]
This is a result of the change in #138. Because args, attributes and modifiers are now evaluated within a callback function, any narrowing on the types of their arguments is lost if those values aren't `readonly`.
