### ISSUE TITLE
Cannot use "built-in" properties like `classNames` for classic components

### ISSUE THREAD

**Issue by boris-petrov** [typed-ember/glint#160]
```typescript
import Component, { ArgsFor } from '@glint/environment-ember-loose/ember-component';

export interface IFoo {}

interface Foo extends ArgsFor<IFoo> {}

class Foo extends Component<IFoo> {}
```

In some other component:

```hbs
<Foo @classNames="something" />
```

This errs with something like:

```
Object literal may only specify known properties, and 'classNames' does not exist in type '{}'.
```

Adding `classNames` to `IFoo` like `readonly Args { readonly classNames?: string }` doesn't help as that then errs with:

```
Interface 'Foo' cannot simultaneously extend types 'Component<IFoo>' and '{ readonly classNames?: string | undefined; }'.
  Named property 'classNames' of types 'Component<IFoo>' and '{ readonly classNames?: string | undefined; }' are not identical.ts(2320)
```

**Comment by dfreeman** [comment]
This is working as intended 🙂 

`classNames` is declared on the base `@ember/component` as `string[]`, and it's part of the backing-class-internal API for tweaking the component's root element. While the snippet you provided does work, it's a side effect of the fact that Ember components splat their args on to the instance (and that writing `classNames: 'foo'` would silently upgrade that string to an array).

We really don't want to treat the entirety of the `@ember/component` API surface area as potential args, as that opens the door to a lot of questionable behaviors (like `<SomeComponent @didInsertElement={{...}} />`), and it also exposes the implementation detail that your component _is_ an `@ember/component` to consumers, which makes it harder to migrate to a Glimmer component in the future.

For classes specifically, `@ember/component`s will also accept a `@class` arg (or, with angle bracket invocation, even a `class` attribute): https://ember-twiddle.com/33b9b7b203a6339c2c5ca5242a58977c?openFiles=templates.application%5C.hbs

**Comment by boris-petrov** [comment]
Alright, fair enough. There is one difference between `classNames` and `class` - for the record - `classNames` doesn't change the added classes if the argument recomputes while `class` does. I guess there is a minor performance difference because of that but no matter, what you say (mostly) makes sense. :) Thanks!

**Comment by boris-petrov** [comment]
@dfreeman - I just hit the same issue with `tagName`. I simply cannot pass `tagName` to a classic component because Glint complains it's not defined in `Args` but when I try to define it, I get the last error from my original post. What am I supposed to do?

**Comment by dfreeman** [comment]
If you define `tagName` identically in your `Args` to the way it's defined on the base type, TS should allow you implement both. Alternatively, you could write `extends Omit<ArgsFor<IFoo>, 'tagName'>`

**Comment by boris-petrov** [comment]
@dfreeman - that's what I also hoped/expected, however defining:

```typescript
  readonly Args: {
    readonly tagName?: string;
  };
```

Lets to:

```
Interface 'Foo' cannot simultaneously extend types 'Component<IFoo>' and '{ readonly tagName?: string | undefined; }'.
  Named property 'tagName' of types 'Component<IFoo>' and '{ readonly tagName?: string | undefined; }' are not identical.ts(2320)
```

Any ideas why?

**Comment by dfreeman** [comment]
Exactly what the error message is saying—your definition of `tagName` isn't the same as the one in `Component`: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/ember__component/-private/view-mixin.d.ts#L30

**Comment by boris-petrov** [comment]
Well, 1) I get the same error even when I remove the `?`:

```
Interface 'Foo' cannot simultaneously extend types 'Component<IFoo>' and '{ readonly tagName: string; }'.
  Named property 'tagName' of types 'Component<IFoo>' and '{ readonly tagName: string; }' are not identical.

22 interface Foo extends ArgsFor<IFoo> {}
             ~~~
```

And 2) that's not what I want. I don't want `tagName` to be *mandatory*, I want it to be optional. Just like it is in an Ember component.

**Comment by dfreeman** [comment]
> Well, 1) I get the same error even when I remove the ?:

Removing the `?` doesn't make it identical if you still have `readonly` 🙂 

> 2) that's not what I want. I don't want tagName to be mandatory, I want it to be optional.

Then I'd go with the other suggestion I made: `extends Omit<ArgsFor<IFoo>, 'tagName'>`.
