### ISSUE TITLE
`{{link-to}}` doesn't accept named args for `route` and `model`

### ISSUE THREAD

**Issue by boris-petrov** [typed-ember/glint#169]
```typescript
import Component from '@glint/environment-ember-loose/glimmer-component';

export default class Foo extends Component {
  foo = 8;
}
```

```handlebars
{{#link-to route="foo" model=this.foo}}
{{/link-to}}
```

```
app/components/foo.hbs:1:1 - error TS2555: Expected at least 2 arguments, but got 1.

1 {{#link-to route="foo" model=this.foo}}
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2 {{/link-to}}
  ~~~~~~~~~~~~

  node_modules/@glint/environment-ember-loose/-private/intrinsics/link-to.d.ts:9:23
    9   (args: EmptyObject, route: string, ...params: unknown[]): AcceptsBlocks<{
                            ~~~~~~~~~~~~~
    An argument for 'route' was not provided.
```

Using:

```handlebars
<LinkTo @route="foo" @model={{this.foo}}>
</LinkTo>
```

Instead fixes the problem.

**Comment by chriskrycho** [comment]
While we should make this work, I have to ask: is there a reason, if you're already doing `route=`, not to just switch to angle brackets? (The codemod works quite well!)

**Comment by boris-petrov** [comment]
Well, a couple of reasons. 1) The codemod didn't work last time I tried it - something blew up. 2) I don't see a reason (for now) to change 90% of my templates and lose sensible git-blame information and whatnot just to use some new syntax (as far as the old one isn't deprecated of course). :) Some day I'll migrate but not for now I hope.
