### ISSUE TITLE
Argument is narrowed to `unknown`

### ISSUE THREAD

**Issue by boris-petrov** [typed-ember/glint#184]
I'm really struggling to name the issues, sorry. :smile: 

Component `Foo`:

```typescript
import Component from '@glint/environment-ember-loose/glimmer-component';

export interface IFoo<T> {
  readonly Args: {
    readonly foos?: readonly T[];
  };

  readonly Yields: {
    readonly default: [foo: T];
  };
}

export default class FooComponent<T> extends Component<IFoo<T>> {}

declare module '@glint/environment-ember-loose/registry' {
  export default interface Registry {
    Foo: typeof FooComponent;
  }
}
```

Component `Bar`:

```typescript
import Component from '@glint/environment-ember-loose/glimmer-component';

export default class BarComponent extends Component {
  public declare x: { foos: any };
}
```

```handlebars
<Foo @foos={{this.x.foos}} as |foo|>
  {{sum foo 3}}
</Foo>
```

With a generic `sum` helper (like the one defined [here](https://github.com/typed-ember/glint/issues/181#issue-867844990)). This leads to:

```
app/components/bar.hbs:2:9 - error TS2345: Argument of type 'unknown' is not assignable to parameter of type 'number'.

2   {{sum foo 3}}
          ~~~
```

**Comment by dfreeman** [comment]
This is how inference in TypeScript works. If you ask it to infer the element type of a non-array type (even `any`) it will give you `unknown` back.

```ts
type GetDefaultYieldFromArgs<T> = T extends { foos: Array<infer El> } ? El : "💥";

type Result = GetDefaultYieldFromArgs<{ foos: any }>;
// Result === unknown
```

Notice that it doesn't infer type `"💥"` there—it knows that `any` extends `Array<infer El>`, but it infers `unknown` for `El`.

To get the behavior it sounds like you want, one option would be to write your signature like this, paramaterized on the array type rather than the element type:

```ts
export interface FooSignature<T extends any[]> {
  readonly Args: {
    readonly foos?: T;
  };

  readonly Yields: {
    readonly default: [foo: T[number]];
  };
}
```

**Comment by boris-petrov** [comment]
@dfreeman - I don't really understand why TypeScript does that and sorry I'm asking a TS-specific question here but in your example the yielded value from the `foo` component will always be typed as `any`, correct? Can I fix this by using:

```ts
export interface FooSignature<T, U extends T[]> {
  readonly Args: {
    readonly foos?: U;
  };

  readonly Yields: {
    readonly default: [foo: U[number]];
  };
}
```

I believe in that case the yielded value will have the correct type (rather than `any`). Am I right and do you think this is better?

**Comment by dfreeman** [comment]
> in your example the yielded value from the foo component will always be typed as any, correct?

It shouldn't. `<T extends any[]>` means `T` needs to extends some array type, but TS will infer a more specific type for `T` if at all possible from context. In this case, if you pass in an actual array of something, it will correctly extract the type, while if you pass in something else (or nothing at all), it will fall back to the widest possible type permitted by the constraint, i.e. `any[]`.

With a component declared like this:

```ts
import Component from '@glint/environment-ember-loose/glimmer-component';

export interface TestSignature<T extends any[]> {
  Args: { foos?: T };
  Yields: { default: [foo: T[number]] };
}

export default class Test<T extends any[]> extends Component<TestSignature<T>> {}

declare module '@glint/environment-ember-loose/registry' {
  export default interface Registry {
    Test: typeof Test;
  }
}
```

| With `@foos` | Without `@foos` |
| --- | --- |
| ![foo: number](https://user-images.githubusercontent.com/108688/126622495-fecca801-a33d-419f-9ed2-d8453c98e2e9.png) | ![foo: any](https://user-images.githubusercontent.com/108688/126622952-a97c13f7-b9e0-4619-9075-cd6569161ea7.png) |

**Comment by boris-petrov** [comment]
That's great to hear. Thank you for the help!
