### ISSUE TITLE
`get` doesn't work with `hash`

### ISSUE THREAD

**Issue by boris-petrov** [typed-ember/glint#185]
```typescript
import Component from '@glint/environment-ember-loose/glimmer-component';

export default class BarComponent extends Component {
  public declare x: 'foo' | 'bar' | 'baz';
}
```

```handlebars
<div class={{get (hash foo="a" bar="b") this.x}}></div>
```

Leads to:

```
app/components/bar.hbs:1:12 - error TS2345: Argument of type 'unknown' is not assignable to parameter of type 'EmittableValue | AcceptsBlocks<{}, any>'.
  Type 'unknown' is not assignable to type 'AcceptsBlocks<{}, any>'.

1 <div class={{get (hash foo="a" bar="b") this.x}}></div>
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Removing `baz` from the type declaration fixes the problem but it should work with it too.

**Comment by dfreeman** [comment]
There are two cascading behaviors being shown here, and I'm not sure which you're saying is the bug, but I think they're both working as expected.

First, when `get` is used with a string that's not known to be a valid key of the object it receives, it returns `unknown`.

Second, we don't allow `unknown` values to be assigned to HTML attributes, for the same reason we don't allow `unknown` values to be emitted directly in top-level mustaches. Emitting a bare object value in a template is nearly always a mistake, and placing any restrictions on the type there at all means we rule out `unknown`.

(Also, I don't think either of these has anything to do with the use of `hash` there—unless I'm missing something, the behavior would be the same if you had defined that object as a class property 🙂)

**Comment by boris-petrov** [comment]
You're absolutely right here, of course. I got confused somehow. Sorry!
