### ISSUE TITLE
Glint doesn't work with the `noPropertyAccessFromIndexSignature` TypeScript option

### ISSUE THREAD

**Issue by boris-petrov** [typed-ember/glint#196]
Setting `noPropertyAccessFromIndexSignature` to `true` in `tsconfig.json` leads to strange errors in `hbs` files.

**Comment by boris-petrov** [comment]
@dfreeman - this hasn't been fixed for the user's case:

```ts
import Component from '@glint/environment-ember-loose/glimmer-component';

class Model {
  [key: string]: any;
}

export default class Foo extends Component {
  public get foo(): Model {
    return new Model();
  }
}
```

```hbs
{{this.foo.bar}}
```

```
app/foo.hbs:1:12 - error TS4111: Property 'bar' comes from an index signature, so it must be accessed with ['bar'].

1 {{this.foo.bar}}
             ~~~
```

**Comment by dfreeman** [comment]
That example seems to be working as expected to me—isn't that error exactly what you're asking TypeScript to flag by setting `noPropertyAccessFromIndexSignature`? 🙂

Wouldn't writing `this.foo.bar` in the backing class somewhere would give you the same error? I would expect to have to write `{{get this.foo 'bar'}}` in the template to avoid that error, given your model type and having that flag enabled.

**Comment by boris-petrov** [comment]
hm, hadn't thought about that. Perhaps you're right... although people would most-likely want that compiler flag for their TypeScript code and not for the HBS templates... not sure. I'll leave the decision to you.
