### ISSUE TITLE
Narrow possibly-undefined value in `each`

### ISSUE THREAD

**Issue by boris-petrov** [typed-ember/glint#212]
Having something like:

```ts
import templateOnlyComponent from '@glint/environment-ember-loose/ember-component/template-only';

class Model {
  readonly foo: readonly number[];
}

interface Foo {
  readonly Args: {
    readonly model: Model | undefined;
  };
}

export default templateOnlyComponent<Foo>();
```

```hbs
{{#each @model.foo as |number|}}
  {{expects-not-undefined @model}}
{{/each}}
```

If `expects-not-undefined` expects `Model` that will fail because `@model` is defined as `Model | undefined`. But this is inside the `each` statement - which loops over a field of `@model`. So `@model` is definitely *not* `undefined` inside the `each` body. It would be nice for Glint to know that.

Not sure if this is possible/easy. Just would be nice.

**Comment by chriskrycho** [comment]
I *believe* this is actually not a limitation of Glint but of TS—see [this playground](https://www.typescriptlang.org/play?#code/C4TwDgpgBAsg9gEwgGygXigbygMznALigDsBXAWwCMIAnAbQF0oBfAKCQGNkBDG6ZCMCjlEKIvCSoAPlFLEkOAJbEICANyt2ELr2g45HYIrjEoEAB6RDAZwBycYAFV5EJSoQAKcuNHIAlEQAbnCK6poikgD8AHR4cLFwNACi3BwAFh4eZFS0fugAfFisUCVmltrAdg7OCsqqXr5+Gsx+rEA) for an equivalent to what you're doing here. Our `{{#each}}` has the same semantics here as that `.forEach()` invocation: it only actually does anything if `@model.foo` actually exists—but the loop body doesn't know that.

**Comment by boris-petrov** [comment]
Yes, I know that, that's why I said that it's not exactly a bug. But Glint is better than TS! :smile: That's why I suggest stuff. :) But feel free to close the issue if you don't think it's possible/needed.

**Comment by dfreeman** [comment]
> But Glint is better than TS!

At the end of the day, Glint _is_ still TS, and I think this is out of scope of what we can make the type system capture 😄
