### ISSUE TITLE
Glint doesn't always recognize component

### ISSUE THREAD

**Issue by bakerac4** [typed-ember/glint#215]
I have noticed recently that sometimes I will have red squigglys over a component that I know I have typed. Hovering over provides the following

```
Element implicitly has an 'any' type because expression of type '"FlSelect::WithTranslationKey"' can't be used to index type 'Globals'.
  Property 'FlSelect::WithTranslationKey' does not exist on type 'Globals'.glint:ts(7053)
```

Sometimes, I see the red squigglys and sometimes it works correctly and can find the component. 

Here is what I see in the logs.
```
 Could not find source file: '/Users/adambaker/Development/gavant/spin-web/spin/app/pods/components/fl-select/with-translation-key/component.ts'.
    at getValidSourceFile (/Users/adambaker/Development/gavant/spin-web/spin/node_modules/typescript/lib/typescript.js:153646:29)
    at Object.getSyntacticDiagnostics (/Users/adambaker/Development/gavant/spin-web/spin/node_modules/typescript/lib/typescript.js:153896:52)
    at GlintLanguageServer.getDiagnostics (/Users/adambaker/Development/gavant/spin-web/spin/node_modules/@glint/core/lib/language-server/glint-language-server.js:83:29)
    at Timeout._onTimeout (/Users/adambaker/Development/gavant/spin-web/spin/node_modules/@glint/core/lib/language-server/binding.js:72:56)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
```

This is particularly frustrating as it makes it near impossible to figure out what you have actually typed correctly and what still needs work

**Comment by dfreeman** [comment]
We chatted a bit in Discord about strategies for tracking down a reproduction here, but an additional thought I had is that it might be useful to emit a synthetic diagnostic from the language server in this situation to let the user know that we aren't properly checking the file. That's obviously a bandaid for the real issue, but might at least be useful to make it clear that something's wrong.

**Comment by dfreeman** [comment]
@bakerac4 #250 updated the language server so that if an exception is raised trying to get diagnostics for a file, we emit an error for that file alerting you to the fact that that's happening. I know it's not as good as actually tracking down the underlying issue, but at least that should hopefully make it more obvious when diagnostics might be missing.

**Comment by dfreeman** [comment]
@bakerac4 are you still running into this issue?

**Comment by bakerac4** [comment]
Haven't paid attention to it in awhile as its just been something I dealt with. You can close for now if you want, and I'll re-open if I see it again?

**Comment by dfreeman** [comment]
👍  Sounds good. Hopefully if you start running into it again we'll be able to track down a way to actually reproduce the issue

**Comment by csprocket777** [comment]
Currently running into this...
