### ISSUE TITLE
broken SSR: environment-glimmerx does not support nodejs modules

### ISSUE THREAD

**Issue by lifeart** [typed-ember/glint#223]
If I use 

```ts
import Component from '@glint/environment-glimmerx/component';
```

ssr build fails with:

```
13:40:24 [vite] Error when evaluating SSR module /node_modules/@glint/environment-glimmerx/component/index.js?v=b8520994:
ReferenceError: exports is not defined
    at /node_modules/@glint/environment-glimmerx/component/index.js?v=b8520994:24:23
    at instantiateModule (C:\Users\lifeart\Documents\repos\glimmerx-workshop\node_modules\vite\dist\node\chunks\dep-55830a1a.js:66458:15)
```

if I replace import with glimmerx default-one, SSR works

It will be great to have this package shipped in 2 types: esm & cjs

**Comment by dfreeman** [comment]
Can you provide a reproduction for this issue? It would surprise me if in general CJS modules were working for the browser but specifically breaking in SSR, especially since CJS is still so common in the Node ecosystem as a whole.

I do see that GlimmerX ships both versions, but I'd love to understand if that's working around some other intrinsic incompatibility between Vite's SSR mode and CJS modules.

**Comment by lifeart** [comment]
may be related: https://github.com/josemarluedke/glimmer-apollo/issues/45

@dfreeman reproduction: https://github.com/lifeart/glimmerx-workshop/tree/glint-ssr-issue-reproduction
steps to get error: `yarn && yarn dev`, visit: `http://localhost:3000`

**Comment by dfreeman** [comment]
As of Glint 0.7.4 native import paths are available, and as of version 0.8.0, Glint no longer exposes any runtime imports itself, so this should no longer be a problem! Check out [the migration guide](https://typed-ember.gitbook.io/glint/using-glint/migrating#glint-0.7.x-to-0.8.0) for further details.

**Comment by knownasilya** [comment]
@lifeart any plans to update your vite plugin?

**Comment by lifeart** [comment]
@knownasilya this update should work without plugin update. But let me know if we could improve smf in `vite-plugin-glimmerx`
