### ISSUE TITLE
[windows] incorrect errors mapping for templates

### ISSUE THREAD

**Issue by lifeart** [typed-ember/glint#224]
![image](https://user-images.githubusercontent.com/1360552/137634960-b295317d-b866-446d-8726-db16cc5c8d58.png)

**Comment by lifeart** [comment]
Double checked results, and it's reproducible only for Windows environment, same error has correct highlighting in mac. Looks like it may be related to different newline delimiters

**Comment by dfreeman** [comment]
Do you have a repo that can reproduce this? Our test suite (including some smoke tests that launch VS Code and verify diagnostic locations) runs in Windows in CI.

**Comment by lifeart** [comment]
@dfreeman yes, 
![image](https://user-images.githubusercontent.com/1360552/140654100-fc3cb79f-ec27-4ef4-9fba-acaba40d37ba.png)


https://github.com/lifeart/glimmerx-workshop/tree/glint-issue

![image](https://user-images.githubusercontent.com/1360552/140654112-e916c96c-9da5-4e4e-90a6-0cf525abdbad.png)
