### ISSUE TITLE
VSCode addon doesn't work for Node 16

### ISSUE THREAD

**Issue by yratanov** [typed-ember/glint#243]
node v16.13.1 (npm v8.1.2)

```
[Error - 10:07:00 PM] Starting client failed
Launching server using command node failed.
```

Works with node 14, though.

**Comment by dfreeman** [comment]
Hi @yratanov, sorry you're running into trouble! I've been playing around with this and don't seem to be able to reproduce the issue. With any of Node 12, 14, 16 or 17 set as my global install on my machine, the extension seems to start up fine.

I even tweaked the language server to include the active Node version in hover info to confirm the right version was being invoked from Code, and it seems to be what I'd expect:

![image](https://user-images.githubusercontent.com/108688/149544356-104a2fce-9914-4d21-8a3e-dd51f09ca5dd.png)

Based on that error message, it sounds like the `node` executable might be missing from the `PATH` that Code is running with? Is there anything different about the way you've installed version 14 vs 16?

**Comment by yratanov** [comment]
hi @dfreeman, thank you for response. It's weird, but now it's working with 16.13.2 for me. Must be something with my config. I'll close the issue.
