### ISSUE TITLE
Bug: Unsafe Call of an any typed value when using `@glint/environment-ember-loose/glimmer-component`

### ISSUE THREAD

**Issue by runspired** [typed-ember/glint#268]
Calling `super` from the constructor results in error: 

> Unsafe call of an `any` typed value.eslint[@typescript-eslint/no-unsafe-call](https://typescript-eslint.io/rules/no-unsafe-call)

Using the regular typings for glimmer component does not result in this error.

```ts
import Component from "@glint/environment-ember-loose/glimmer-component";
import type { Notification } from "frontend/services/notifications";

interface Args {
  notification: Notification;
  onDismiss?(notification: Notification): void;
}

export interface NotificationCardSignature<T> {
  Element: HTMLDivElement;
  Args: T;
  Yields: {};
}

export default class NotificationCard extends Component<
  NotificationCardSignature<Args>
> {
  declare args: Args;

  constructor(owner: unknown, args: Args) {
    super(owner, args);
  }
}
```

**Comment by dfreeman** [comment]
This sounds like a symptom of something else going wrong. A few questions:
 - Do you have `skipLibCheck` turned on in your `tsconfig`? That might mask the reason `Component` is being typed as `any`.
 -  Why do you have `declare args: Args`? If you needed that for `this.args` to be typed properly, that also points to the type of `Component` itself being incorrect.
 - Is `Component` treated as thought it has type `any` under `tsc`? Under `glint`?

**Comment by runspired** [comment]
as I can no longer debug this particular instance I'm going to close this, but I suspect skipLibCheck was on. Component was not an `any`, that much I do remember.
