### ISSUE TITLE
Make clear the path for incremental adoption

### ISSUE THREAD

**Issue by runspired** [typed-ember/glint#269]
Currently there is no ability to configure what templates might receive type checking, so applications migrating from JS to TS thinking of adopting glint see this as all-or-nothing.

**Comment by dfreeman** [comment]
This is exactly the purpose of [the `include` glob(s)](https://github.com/typed-ember/glint#getting-started) in your `.glintrc` 🙂

**Comment by runspired** [comment]
@dfreeman is that documented some place?

**Comment by chriskrycho** [comment]
He linked directly to the docs. 😅

**Comment by simonihmig** [comment]
I think an `exclude` option would also be helpful. Say you have `app/components/special/` that you want to exclude, but don't want to explicitly write dozens of `include` to include all the possible siblings of `special`, like:

```yaml
include:
- app/components/**
exclude:
- app/components/special/**
```
