### ISSUE TITLE
Passing file to CLI does not work

### ISSUE THREAD

**Issue by simonihmig** [typed-ember/glint#274]
`glint --help` suggest you can pass the file you want to check:

```bash
> glint --help
glint [options] [file...]
```

But whatever you pass, a path to an existing (invalid!) hbs file or just `.`, it will return without any console output and with an exit code of zero!

**Comment by dfreeman** [comment]
That's a bug in the help text for the CLI—we should really remove the indication that operating on single files is viable.

We were originally mirroring `tsc`'s CLI more closely, but realistically Glint can't perform useful typechecking of an individual file, particularly in the context of a loose-mode Ember app where you need registry information that's scattered throughout a project.
