### ISSUE TITLE
Document common error messages

### ISSUE THREAD

**Issue by dfreeman** [typed-ember/glint#28]
In general I think error messages should be relatively easy to map from TypeScript terms to what's happening in the template, but it's quite possible there will be situations where an error message is nonobvious if you don't know how the template is being translated to TS. JSX is _natively_ supported by the compiler and still has this problem, and even just in vanilla TypeScript authors sometimes struggle to understand what a type error is trying to tell them.

Given that we have the original template AST node available when we're emitting error messages, we may be able to eventually bake in "Hint: this may mean you forgot to do XYZ" help when certain error codes pop up on certain node types, but in the meantime we should be keeping an eye out for common situations that may not be easy to diagnose for anyone not familiar with glint internals.

**Comment by chriskrycho** [comment]
@dfreeman does the one from Dec. 2020 still need docs! Since I started adding those kinds of things in #318, I figured I’d check!

**Comment by dfreeman** [comment]
Here's another: this happens when you try and pass a function as an attribute value.

Technically this works today if the attribute corresponds to a prop of the same name on the DOM element, but the prop/attr confusion is something the community has talked about moving away from in the future, and the behavior of assignments like this in a world with the default helper manager RFC in place is still iffy.

```
app/components/some-template.hbs:1:17 - error TS2345: Argument of type '() => void' is not assignable to parameter of type 'EmittableValue | AcceptsBlocks<{}, any>'.
  Property '[Element]' is missing in type '() => void' but required in type 'AcceptsBlocks<{}, any>'.

1 <button onclick={{this.toggle}}>
                  ~~~~~~~~~~~~~~~

  node_modules/@glint/template/-private/integration.d.ts:41:3
    41   [Element]: El extends Element ? El : null;
         ~~~~~~~~~
    '[Element]' is declared here.

  app/components/some-template.hbs:1:17 
    1 <button onclick={{this.toggle}}>
                      ~~~~~~~~~~~~~~~
    Did you mean to call this expression?
```

**Comment by dfreeman** [comment]
https://discord.com/channels/480462759797063690/484421406659182603/978754236466728960

**Comment by dfreeman** [comment]
#342 brought up a key one: the disparity between the number of visible positional args and the number we report in diagnostics. Because named args are always passed as the first arg, TS sees `{{go 'foo'}}` as `go({}, 'foo')`, which means if you do something like passing a positional arg where none is expected, `{{go 'foo'}}` will say "Saw 2 args but expected 1", which is super confusing.
