### ISSUE TITLE
Missing @glimmer/component dependency

### ISSUE THREAD

**Issue by ef4** [typed-ember/glint#282]
`@glint/environment-ember-loose` depends on `@glimmer/component`:

https://github.com/typed-ember/glint/blob/e75e5806d17a640d2711c1b2c176b53bd0005aab/packages/environment-ember-loose/glimmer-component/index.ts#L15

but only declares it as a devDependency, which means you're at the mercy of what the package manager happens to expose.

In my case, I was seeing `@glimmer/component` 1.0.4 which lacks the `EmptyObject` type, causing a type error.

This can probably be a peerDependency, so that it's clear that the app needs to have a compatible version.

**Comment by dfreeman** [comment]
This will be true in the 0.8 release, but currently the `EmptyObject` type comes from elsewhere in Glint (you can see the import further up in that file)

For 0.8 where we drop all our shenanigans with reexports, we'll be declaring proper peerDeps.

**Comment by ef4** [comment]
Oh I see, so this is already fixed on main.

**Comment by dfreeman** [comment]
Or will be soon, at least :)

Thank you for the report!
