### ISSUE TITLE
glint doesn't parse args with dashes correctly

### ISSUE THREAD

**Issue by nlfurniss** [typed-ember/glint#284]
### Summary
If you have a component arg that has a dash in the name, glint does not handle it correctly.

### Error
```hbs
// template file

<p>You passed in {{@example-arg}}</p>
```

```sh
$ yarn glint

app/components/example-component.hbs:2:20 - error TS2304: Cannot find name 'arg'.

2   You passed in {{@example-arg}}
                     ~~~~~~~~~~~

app/components/example-component.hbs:2:20 - error TS2339: Property 'example' does not exist on type '{ 'example-arg': string; }'.

2   You passed in {{@example-arg}}
                     ~~~~~~~~~~~
```

This [demo repro](https://github.com/nlfurniss/glint-repro#glint-repro) shows the issue, and contains one commit where a camel case arg works `ExampleArg` but a dasherized one does not

**Comment by dfreeman** [comment]
I would've sworn we handled non-`Identifier`-args correctly, but clearly we don't! 😄 

Thank you for the thorough report and reproduction, @nlfurniss—hopefully we should be able to get this taken care of during the flurry of activity over the next day or so.
