### ISSUE TITLE
Regression when using native imports for modifier

### ISSUE THREAD

**Issue by simonihmig** [typed-ember/glint#293]
I just updated to the latest release (0.7.4) and changed imports to the native ones. Everything (components, helpers) worked except for this modifier:

```ts
import { modifier } from 'ember-modifier';
import { assert } from '@ember/debug';

const autofocusModifier = modifier(function autoselect(element, _positional, { event = 'click' }: { event?: string }) {
  assert(
    'autoselect modifier expects an input or textarea element.',
    element instanceof HTMLInputElement || element instanceof HTMLTextAreaElement
  );
  const selectAll = (): void => element.select();

  element.addEventListener(event, selectAll);

  return (): void => {
    element.removeEventListener(event, selectAll);
  };
});

export default autofocusModifier;

declare module '@glint/environment-ember-loose/registry' {
  export default interface Registry {
    autoselect: typeof autofocusModifier;
  }
}
```

With the old imports there were no problems, but with the native one (from `ember-modifier`), I get this in a template:

```
app/components/modal/save.hbs:22:13 - error TS2769: No overload matches this call.
  Overload 1 of 2, '(item: DirectInvokable<AnyFunction>): AnyFunction', gave the following error.
    Argument of type 'unknown' is not assignable to parameter of type 'DirectInvokable<AnyFunction>'.
  Overload 2 of 2, '(item: (abstract new (...args: unknown[]) => Invokable<AnyFunction>) | null | undefined): (...args: any) => any', gave the following error.
    Argument of type 'unknown' is not assignable to parameter of type '(abstract new (...args: unknown[]) => Invokable<AnyFunction>) | null | undefined'.

22           {{autoselect}}
```

**Comment by dfreeman** [comment]
The fact that `autoselect` has type `unknown` suggests that something may be going on with `ember-modifier` more genereally rather than Glint specifically. If you hover `autofocusModifier` in your snippet above, does it also show type `unknown` there?

**Comment by simonihmig** [comment]
> The fact that autoselect has type unknown suggests that something may be going on with ember-modifier more generally rather than Glint specifically. If you hover autofocusModifier in your snippet above, does it also show type unknown there?

Yes, it does (did)...

> Can you also confirm what version of ember-modifier you're on? There were a few late-added fixes to the types there last as well.

That was the culprit indeed. I still had `3.1.0` (our renovate bot only updated it a few days ago, so that was missing still on my feature branch). After updating to the latest (`3.2.7`), it works fine again!

Thanks for the help!
