### ISSUE TITLE
TS can't find registry when declaring component templates

### ISSUE THREAD

**Issue by nlfurniss** [typed-ember/glint#317]
### Background
* glint 0.8.0 (though happened in 0.7.x) too
* @glint/environment-ember-loose is a dev dep in package.json and in packages/addons/ADDON/package.json
* Ember app is using yarn workspaces

I'm working on the same project @chriskrycho is, and trying to declare the templates for components inside an in-repo-addon like so:

```js
declare module '@glint/environment-ember-loose/registry' {
  export default interface Registry {
    Addon$Component typeof ThisComponent;
    'addon@component': typeof ThisComponent;
  }
}
```
This must be working because it fixes errors in between runs of `yarn glint`, however, TS throws this error: `Invalid module name in augmentation, module '@glint/environment-ember-loose/registry' cannot be found.ts(2664)`

Has anyone seen this before?

**Comment by dfreeman** [comment]
That error is essentially TypeScript's way of saying "you're trying to augment a module, but I haven't seen the module you're trying to augment".

In this instance, that suggests that you don't have `import '@glint/environment-ember-loose';` (which ensures that the "root" version of that registry module is included) somewhere in your project that it would be visible to TS from that in-repo addon.

Do you have separate `tsconfig` files for your in-repo addons versus your base app?

**Comment by nlfurniss** [comment]
Yes, in the root dir I have `types/APP_NAME/index.d.ts` which contains `import '@glint/environment-ember-loose';` on the first line. In my in-repo addon I have a tsconfig that looks like:

```json
{
  "extends": "../../../tsconfig.base.json", // App-wise config
  "include": ["addon", "tests"]
}

```
`

**Comment by dfreeman** [comment]
That config snippet points to what the issue may be 🙂 

Since you only have the addon's own `addon` and `tests` directories in your `include`, when `tsc` or `tsserver` attempts to typecheck it, the `types` directory in the root isn't visible to it, so none of the augmentations from `@glint/environment-ember-loose` will be applied. You'll likely want to either add that import somewhere a declaration in the addon itself, or add the root `types` directory to your addon's `include` array.

**Comment by chriskrycho** [comment]
We confirmed that that is indeed the issue: we have the desired `include` in our root, but it wasn't clear to the folks who set up the `tsconfig.json` that `include` *stomps* rather than *merges* with the value from whatever is being `extends`'d.

**Comment by nlfurniss** [comment]
Is this too much a user error to include in the docs?

Just thinking for fellow error-ridden travelers.

**Comment by chriskrycho** [comment]
Not at all! #318 aims at starting a docs page for exactly these kinds of things. (It wasn’t obvious to me at first, either, so I sure as heck wouldn't expect it to be obvious to ordinary Glint users!)
