### ISSUE TITLE
Document: ambient types vs. TS conversion

### ISSUE THREAD

**Issue by chriskrycho** [typed-ember/glint#322]
Our docs currently cover the path where you are providing types for TypeScript code. A fairly common situation across the ecosystem will be writing ambient type definitions for JavaScript code—for legacy code which won't be converted to TS but needs type definitions, for libraries whose authors will accept PRs adding ambient types but aren’t interested in adopting TS themselves, etc. We should document how to do that!

**Comment by chriskrycho** [comment]
Note: we have *some* of this already under [Typing Your Dependencies](https://github.com/typed-ember/glint/blob/main/docs/ember/typing-your-dependencies.md). Would just be good to elaborate.

**Comment by dfreeman** [comment]
I believe this is now covered thanks to @simonihmig under https://typed-ember.gitbook.io/glint/using-glint/ember/authoring-addons#adding-glint-types-to-addons-not-written-in-typescript 🎉

**Comment by simonihmig** [comment]
I agree on having this covered in the docs, but I disagree on giving me credit for this. AFAIR I was not involved in writing that section! 😅

**Comment by dfreeman** [comment]
Ah, [my mistake](https://github.com/typed-ember/glint/commit/1b306d15fa33f619cc3ad6f178938e143c4443da). Thank **you** @jamescdavis!
