### ISSUE TITLE
Support shipping Glint types with v2 addons

### ISSUE THREAD

**Issue by simonihmig** [typed-ember/glint#338]
> This issue is not a call to action, but meant to document and track the status quo of how to ship Glint types with v2 addons for better visibility here. I will try to keep it up to date, whenever new insights emerge...

We have already figured out and documented how an addon (v1) should ship its own Glint-based types. This should also be possible for a v2 addon, in the same manner (from the consumer's perspective). However a first experiment doing that was that successful yet (https://github.com/kaliber5/ember-stargate/pull/494)...

The main problem was how to tell TS where to find the `my-addon/glint` module that an app is supposed to import (for the automatic registry registration of its components). While the v2 format does not require any kind of build step per se, most existing v2 addons have that (a pre-*publish* build step that is), and the [v2 addon blueprint](https://github.com/embroider-build/addon-blueprint) also has that baked in. The compiled artefacts will then usually live in a `./dist` folder. Webpack (used by Embroider or ember-auto-import) will know how to resolve the imported modules to this folder on disk by making use of the `exports` feature of the [addon's `package.json`](https://github.com/embroider-build/addon-blueprint/blob/main/files/packages/__name__/package.json#L61-L65). While this is well supported by Webpack and Node, only the upcoming TS 4.7 will add support for it. Which is needed to make the import of the addon types (`my-addon/glint`) work correctly. So the app would need to be on TS 4.7 to "just work", for older TS versions a manual `paths` entry in `tsconfig.json` would be required. 

*However* even with 4.7 beta, I was not able to make it work (see linked PR above). My IDE would correctly resolve the imported Glint types, but `glint` itself apparently not, continuing to complain due to the addons's components not being added to the registry. 🤔  This needs further investigation...

**Comment by dfreeman** [comment]
Disclaimer: this is only based on reading that PR, not actually pulling if down and poking it with the typechecker, so I could be wrong! That said:

I _think_ what you're hitting there isn't actually specific to Glint, but a more general issue that v2 TS addons are going to have to contend with for a while. Setting `exports` alone isn't enough to make the consumer aware of the path mapping: they also need to set `moduleResolution: 'node16'` in their `tsconfig.json` in order to opt in to honoring the `exports` field in their dependencies' `package.json` files. Anyone still using `moduleResolution: 'node'` will see TypeScript continue to try to resolve paths directly on-disk as before.

One way to work around this and support both `moduleResolution: 'node'` and `moduleResolution: 'node16'` in consumers for the time being would be with `typesVersions`. I may not have the notation exactly right, but I think something along these lines should work:

```json
  "exports": {
    "./addon-main.js": "./addon-main.js",
    "./*": {
      "types": "./dist/*.d.ts",
      "default": "./dist/*.js"
    }
  },
  "typesVersions": {
    "*": {
      "*": ["dist/*"]
    }
  }
```

**Comment by simonihmig** [comment]
Hey Dan, this is *very* valuable feedback, thank you! I didn't realize that support for the `exports` key was coupled to `node16`, should have read the whole announcement post... 🙄

Will try out your suggestions and report back!

**Comment by NullVoxPopuli** [comment]
So, I have a different issue, but related to the theme of shipping Glint types with v2 addons (mostly for loose ember),

<details><sumary>I have these files</summary>

// in the addon
```ts
// glint.d.ts
import '@glint/environment-ember-loose';
import '@glint/environment-ember-loose/native-integration';

import type { PopperJS } from './dist/index';

declare module '@glint/environment-ember-loose/registry' {
  export default interface Registry {
    'popper-j-s': typeof PopperJS;
    PopperJS: typeof PopperJS;
  }
}
```
```js
// package.json
 "files": [
    "dist",
    "glint.d.ts",
    "addon-main.cjs"
  ],
    "exports": {
    ".": "./dist/index.js",
    "./*": "./dist/*"
  },
  "typesVersions": {
    ">=4.0.0": {
      "*": [
        "dist/*"
      ],
      "glint": [
        "glint.d.ts"
      ]
    }
  },
```

then in my test-app (which had the latest ember-cli-typescript blueprint applied recently):
```yml
# .glintrc.yml

environment:
  - ember-loose
  - ember-template-imports
include:
  - 'app/**'
  - 'tests/**'
```

```ts
// types/test-app/glint-registry.d.ts
import "@glint/environment-ember-loose";
import "@glint/environment-ember-loose/native-integration";
import "ember-page-title/glint";
import "ember-popperjs/glint";

declare module "@glint/environment-ember-loose/registry" {
  export default interface Registry {
    // App-specific overrides here
  }
}
```


</details>

My error(s):

```
(property) Registry.PopperJS: typeof PopperJS
----------------------------
Property 'template' does not exist on type 'typeof import("/home/nullvoxpopuli/Development/NullVoxPopuli/ember-popperjs/testing/test-app/node_modules/@glint/environment-ember-loose/-private/dsl/index")'.glint:ts(2339)
---------------------------
Parameter '𝚪' implicitly has an 'any' type.glint:ts(7006)
----------------------------
Property 'emitComponent' does not exist on type 'typeof import("/home/nullvoxpopuli/Development/NullVoxPopuli/ember-popperjs/testing/test-app/node_modules/@glint/environment-ember-loose/-private/dsl/index")'.glint:ts(2339)
----------------------------
Property 'resolve' does not exist on type 'typeof import("/home/nullvoxpopuli/Development/NullVoxPopuli/ember-popperjs/testing/test-app/node_modules/@glint/environment-ember-loose/-private/dsl/index")'.glint:ts(2339)
----------------------------
No quick fixes available
```

**Comment by chriskrycho** [comment]
@NullVoxPopuli I moved that to a different issue to avoid cluttering up this one for its original purpose.

**Comment by simonihmig** [comment]
I tried this, but failed miserably, idk what's wrong...

I had TS updated, added `exports`, `typesVersions` and `node16` etc., but this was not working. TS would basically not see the added registry items, complaining about `...  can't be used to index type 'Globals'.`.

I then reverted the changes and tried to get to a working state with the most simple setup:
* using TS 4.6 and the normal `node` module resolution
* having an explicit `paths` config to [point to the addon's `glint.d.ts`](https://github.com/kaliber5/ember-stargate/pull/494/files#diff-be6974f5c44ccf1a76788dc32d9eb836693ac2a8fa784e479d5dbe774c4f4e46R76)

Still I am getting the same errors, when running `yarn lint:ts` (alias for `glint`) inside the `test-app`. 

Then added [this commit](https://github.com/kaliber5/ember-stargate/pull/494/commits/30db7f52a3b7a9a921d1e9b6ddec1a8ea08e8689) to test what's happening:
* `pageTitle` is correctly typed, defined in the [test-app's glint.d.ts](https://github.com/kaliber5/ember-stargate/pull/494/files#diff-5e8f01df3322b94b4b89dba74176baf5029e6ae3da59c08b6c07baa560f8080bR7-R10)
* but `portal` has an `any` type and TS complains about `Property 'Portal' does not exist on type 'Registry'`, despite importing `ember-stargate/glint` (without errors, as it exists correctly in the addon's `dist/glint.d.ts`) which has the right registry declarations [here](https://github.com/kaliber5/ember-stargate/pull/494/files#diff-ce736dc8722b677e2a782895dae87ef1d786ff513716f46226af648f7f9557aaR6)
* when I copy paste the addon's `glint.d.ts` into the test-app (and fix the import paths), then it works correctly. As if it ignores the registry interface augmentation when coming from the external addon only!? 

What am I missing? 😟

**Comment by dfreeman** [comment]
> As if it ignores the registry interface augmentation when coming from the external addon only!?

This sounds similar to what you'd see with linked packages or another setup where the addon and host app have distinct copies of the package providing the registry. I'll pull the code from your PR later today and see if anything jumps out at me

**Comment by simonihmig** [comment]
> This sounds similar to what you'd see with linked packages or another setup where the addon and host app have distinct copies of the package providing the registry. 

@dfreeman Oh, yes, this was it! Thanks again! I accidentally had slightly different versions of glint deps (0.8.0 vs. 0.8.2) in my lockfile, for the v2 addon vs. the test-app. After deduping, everything works again as expected! :tada:

**Comment by simonihmig** [comment]
So, after adding proper `exports`[^1] and `typesVersions` (and upgrading `rollup-plugin-ts` to the just released v3 to let babel do all the transpilation), things are working fine now, both with TS 4.6 and 4.7 (using `node16`)! 

Closing this, as I would consider it a solved problem now. For reference, this is the passing PR again: https://github.com/kaliber5/ember-stargate/pull/494


[^1]: `"default": "./dist/*.js"` had to be changed to `"default": "./dist/*"`, otherwise webpack wouldn't resolve a module when imported using a `.js` ending.

**Comment by dfreeman** [comment]
> We must not strip the extension, or else it becomes invalid in Node’s resolution. 

Extensions are only required for relative imports though, aren't they? My understanding is that for absolute (package-name-rooted) imports like the app reexports, you have to follow whatever pattern is established by `exports`, and it _seems_ like the norm is not to include extensions.

**Comment by ef4** [comment]
> We must not strip the extension, or else it becomes invalid in Node’s resolution

That's true as a default but it's under the control of each package's `exports` property. If a package wants consumers to import from extensionless paths, Node supports that. It's probably a best practice to do so.
