### ISSUE TITLE
[VSCode] Glint not running in project which is sub-folder within CWD

### ISSUE THREAD

**Issue by NullVoxPopuli** [typed-ember/glint#343]
I have two VSCode instances open
 - one at the root of my monorepo
    - when I open my -test.ts file, I get no errors
 - one at the root of the test app (which is two directories down from the root of the monorepo, but that doesn't matter really)
    - when I open my -test.ts file, I get a bunch of errors
    
This leads me to believe that Glint didn't start when VSCode was open in the root of the monorepo.

I did not have this problem with neovim, so I think it might be an issue specific to the VSCode extension?

**Comment by dfreeman** [comment]
This is a [documented limitation](https://typed-ember.gitbook.io/glint/using-glint/known-limitations) of the way the VSC extension handles language server instantiation. We're planning to fix that as part of a more general effort to overhaul configuration soon.
