### ISSUE TITLE
When installing @glint/template to provide types via HelperLike, etc, I get an error about @glimmer/component being a missing peer

### ISSUE THREAD

**Issue by NullVoxPopuli** [typed-ember/glint#347]
```
 WARN  Issues with peer dependencies found

└─┬ @glint/template
  └── ✕ missing peer @glimmer/component@^1.1.2
Peer dependencies that should be installed:
  @glimmer/component@^1.1.2  

```

My library _shouldn't_ add `@glimmer/component` as a peer dependency, so I'm wondering if `@glint/template` maybe needs to set `@glimmer/component` as an option peer dependency or if there should be a separate package for just helper types?
idk

**Comment by dfreeman** [comment]
I'm going to leave it to you to suggest a path forward here, as you're the person driving `pnpm` usage in the community therefore likely to have the most firsthand experience with what common pain points and possible remedies are for its stricter handling `peerDependencies`.

Currently we need `@glimmer/component` for its `ExpandSignature`, though, so just setting it as an optional peer isn't viable.

**Comment by NullVoxPopuli** [comment]
>  driving pnpm 

fwiw, I _think_(? haven't confirmed) that yarn3 gives the same warnings / errors -- though I'm not sure if yarn3 does "strict peers" like pnpm7 does (pnpm 7 is like.. a month or two old and previously didn't error on peer violations).

> Currently we need @glimmer/component for its ExpandSignature, though, so just setting it as an optional peer isn't viable.

makes sense!
I figured that'd be the case as I was poking around in there for some other stuff I was looking at.

So, for library authors/consumers of `@glint/template`, what _can_ be done is to use a `pnpm` entry in the package.json

mine currently looks like this:

```js
  "pnpm": {
    "peerDependencyRules": {
      "ignoreMissing": ["@glimmer/component"],
    }
```

I _think_ this should be ok? at least, _for now_, I haven't ran in to any issues with `@glimmer/component` _not_ being a dependency in my library -- I imagine the dep is being resolved elsewhere (or not used) as I'm only relying on `HelperLike` atm.

**Comment by NullVoxPopuli** [comment]
I kind of also wonder if `ExpandSignature`  would benefit from living in some types-only package? `@glint/types` perhaps? (idk) could host a bunch of stuff, and have no runtime or additional dependencies?

**Comment by dfreeman** [comment]
That's already what `@glint/template` is, but like we've talked about, `ExpandSignature` isn't a Glint-specific thing.

The `@glimmer/component` package needs that type to determine e.g. the type of `this.args`

**Comment by NullVoxPopuli** [comment]
Gonna close this for now as the `peerDependencyRules` seems sufficient for now.

If they cause any problems, I'll re-open.

**Comment by NullVoxPopuli** [comment]
Separate guidance for addons:
```
  "pnpm": {
    "peerDependencyRules": {
      "ignoreMissing": [
        "webpack",
        "ember-cli-htmlbars"
      ]
    }
  },
```

and then, `@glimmer/component`, etc (any other upstream peer) should be forwarded to the consumer of `<your addon>`.
(devDep (for types) + peerDep (for runtime resolving))

Thankfully, all apps consuming addons will already have `@glimmer/component`.

The downside, is that the more addons that forward peers, the more gnarly peer error will get, as we'll have a lot of (nearly)redundantly reported information.
