### ISSUE TITLE
Handle template-only components

### ISSUE THREAD

**Issue by dfreeman** [typed-ember/glint#37]
Currently template-only components are unsupported. There are a few ways we might possibly go, but in the short term the simplest path forward might be to support having a `.d.ts` file alongside a template that can declare its associated type(s). Longer-term, as the community adopts standards for strict-mode templates and we see how that ends up looking, we can consider ways to define the types in the same file as the template itself.

```hbs
{{! app/components/my-component.hbs }}

{{@name}} said:

<blockquote>{{yield to="quote"}}</blockquote>
```

```ts
// app/components/my-component.d.ts

import Component from '@glimmer/component';

export interface MyComponentArgs {
  name: string;
}

export interface MyComponentYields {
  quote: [];
}

export default class MyComponent extends Component<MyComponentArgs, MyComponentYields> {}
```

**Comment by boris-petrov** [comment]
I currently have something like:

```typescript
import { AcceptsBlocks, DirectInvokable, EmptyObject } from '@glint/template/-private/integration';

type FooComponent = DirectInvokable<(args: { readonly arg1: string; readonly arg2: number }) => AcceptsBlocks<{}>>;

declare module '@glint/environment-ember-loose/registry' {
  export default interface Registry {
    'foo-component': FooComponent;
  }
}
```

Which, I believe, works fine for template-only components. Am I wrong? I guess the only reason this is not "recommended" or mentioned in the README is because it uses private stuff?

**Comment by dfreeman** [comment]
You could do what you're doing there without touching private API by writing something like this:

```ts
import Component from '@glint/environment-ember-loose/glimmer-component';

declare class FooComponent extends Component<{
  Args: { arg1: string; arg2: number };
}> {}

declare module '@glint/environment-ember-loose/registry' {
  export default interface Registry {
    'foo-component': typeof FooComponent;
  }
}
```

That works to make `foo-component` usable elsewhere in your app, and could even go in a `.d.ts` file alongside your template if you wanted, but the thing that's still missing is typechecking within `FooComponent`'s template.

Currently we don't do any analysis at all for templates we can't locate a backing class for, so we can't really say we support template-only components until we can actually ensure that they actually adhere to the signature you declare for them.

**Comment by wagenet** [comment]
I've been making `.d.ts` files for these which helps with external calls, but I don't get glint support inside the templates themselves. Though maybe once you're making `.d.ts` files you should just make it a classy component?
