### ISSUE TITLE
Invalid `{{component}}` first arg leads to a confusing message

### ISSUE THREAD

**Issue by dfreeman** [typed-ember/glint#373]
In `ember-loose`, where `{{component}}` accepts a string as its first value, typoing the name of your component gives an error like:

```
TS2769: No overload matches this call.
  The last overload gave the following error.
    Argument of type 'string' is not assignable to parameter of type 'abstract new (...args: unknown[]) => Invokable<(args: unknown) => AcceptsBlocks<any, any>>'
```

While this is technically true, it's super confusing. At a bare minimum if we see a string literal as the first arg, we should probably suggest that you check for typos and that you haven't forgotten to add a registry entry.

**Comment by boris-petrov** [comment]
@dfreeman I believe this is still somewhat of an issue. When I use `#component` (that is, the block form) of the `component` helper - I get a nice error message that this is not supported by Glint and I should convert that usage. But I don't get any error message when using `component` in the "normal" form - and there some stuff doesn't work. So it would be nice to have an error message for that case too.

**Comment by dfreeman** [comment]
> some stuff doesn't work

This doesn't really tell me anything about what's going wrong 😉 

Can you open a new issue with a description of what's not working?
