### ISSUE TITLE
Don't crash on unrecognized file types

### ISSUE THREAD

**Issue by wagenet** [typed-ember/glint#380]

**Comment by dfreeman** [comment]
This can happen in `.js` files with `allowJs: false`, or `.gts`/`.gts` files when the `ember-template-imports` environment isn't active. It manifests as `Error: Could not find source file` from TypeScript when calling into the language service for e.g. definition info.

**Comment by dfreeman** [comment]
Looking back over our conversation in Discord and the code here, were you actually seeing a crash @wagenet? We do log these errors, but I can't see how this would have brought down the language server.

**Comment by wagenet** [comment]
@dfreeman I was seeing crashes, but I guess this wasn’t actually the culprit.
