### ISSUE TITLE
Meta issue: function helper resolution bugs

### ISSUE THREAD

**Issue by dfreeman** [typed-ember/glint#396]
I'm opening this to track issues with function helpers that we expect will be fixed with our [planned overhaul](https://tsplay.dev/mM1zQm) of the internal representation of invokable template entities within Glint.

**Comment by dfreeman** [comment]
### `unknown` is treated as named-args-like

Given this function,
```ts
declare function isEqual(a: unknown, b: unknown): boolean;
```

This will resolve as a helper with one positional arg and shapeless named args.

**Comment by dfreeman** [comment]
### Named-args-like args _have_ to be passed as named args

Given this function:
```ts
declare function constructLanguageTag(options: { country: string; language: string }): string;
```

This should be legal to invoke as either of the following:
```hbs
{{constructLanguageTag country="US" language="en"}}
{{constructLanguageTag (hash country="US" language="en")}}
```

However, currently only the former is accepted.

**Comment by boris-petrov** [comment]
### Class args don't work in any way

Given:

```ts
class Foo {}
const someFooInstance: Foo;
declare function handleFoo(foo: Foo): string;
```

This should be legal:

```
{{handleFoo someFooInstance}}
```

However, currently there is an error - `Expected 0 arguments, but got 1`.

**Comment by dfreeman** [comment]
Not a helper resolution bug, but something we should verify as part of overhauling `[Invoke]`: we should make sure assignability works as expected with `ComponentLike`, `WithBoundArgs`, etc.

As a concrete example, this component:

```ts
class MyComponent extends Component<{
  Args: { foo?: string };
  Element: HTMLImageElement;
  Blocks: { default: [] };
}> {}
```

Should be assignable to (among other things) `ComponentLike` with no parameters, since it's legal to invoke with no args, `...attributes` or blocks.
