### ISSUE TITLE
Property 'template' does not exist on type

### ISSUE THREAD

**Issue by csprocket777** [typed-ember/glint#400]
I have a component I've written using `ember-cli-typescript` that I'm trying to augment to use Glint. In case it's pertinent, it's using an inheritance structure (which I'm working to convert away from).

I was encountering issues in the process that I couldn't solve and in a moment of insanity thought I'd try moving to using first-class templates to try and solve my woes. Realizing I was adding too many variables to the mix, decided to back-track out of that process and get back to my original build issue in glint.

In the process of back-tracking out of using first-class component templates, I ended up with an issue that glint reported that I couldn't solve and am currently "stuck".

**Error:**
Using `glint --watch`:
```javascript
addon/ember-cui-base-component.hbs:1:1 - error TS2339: Property 'template' does not exist on type 'typeof import("/Users/...pathToComponent.../ember-cui-alt/node_modules/@glint/environment-ember-loose/-private/dsl/index")'.

  1

  2 {{#let (element this.tagName) as |Tag|}}
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
...
 12     </Tag>
    ~~~~~~~~~~
 13 {{/let}}
    ~~~~~~~~

addon/ember-cui-base-component.hbs:1:1 - error TS2694: Namespace '"/Users/...pathToComponent.../ember-cui-alt/node_modules/@glint/environment-ember-loose/-private/dsl/index"' has no exported member 'ResolveContext'.

  1

  2 {{#let (element this.tagName) as |Tag|}}
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
...
 12     </Tag>
    ~~~~~~~~~~
 13 {{/let}}
```

**My environment:**
```
ember-cli: 3.28.5
node: 16.13.1
os: darwin arm64
```

Here is a repo that replicates the issue:
https://github.com/csprocket777/glint-component-error-repro

**Comment by dfreeman** [comment]
@csprocket777 I've cloned your repo and wasn't able to reproduce the issue you're describing. The only type error I get from Glint is this one (which, as I've suggested in Discord, you should be able to resolve by only making the `Args` to your base component generic rather than its entire signature):

```
addon/ember-cui-base-component.hbs:11:17 - error TS2345: Argument of type '[string]' is not assignable to parameter of type 'NonNullable<FlattenBlockParams<ExpandSignature<Signature>["Blocks"]>["default"]>'.
  Type '[string]' is not assignable to type 'ExpandSignature<Signature>["Blocks"]["default"] extends { Params: { Positional: infer U; }; } ? U : ExpandSignature<Signature>["Blocks"]["default"]'.

11         {{yield this.elementId}}
                   ~~~~~~~~~~~~~~


11:47:07 AM - Found 1 error. Watching for file changes.
```

Have you seen this issue on any other machine? I wonder if you may have some corruption in your local npm cache that would explain why you seem to be getting the wrong version of `@glint/transform`.

**Comment by csprocket777** [comment]
Trying to figure out what corruption I have locally that produces this error, this is what yarn is saying about `@glint/transform`:
```javascript
yarn list --pattern "@glint/transform"
yarn list v1.22.17
warning Resolution field "responselike@1.0.0" is incompatible with requested version "responselike@^3.0.0"
warning Resolution field "responselike@1.0.0" is incompatible with requested version "responselike@^2.0.0"
warning Resolution field "got@12.4.1" is incompatible with requested version "got@^10.5.2"
warning @semantic-release/npm > npm > node-gyp > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning Resolution field "got@12.4.1" is incompatible with requested version "got@^6.7.1"
warning Resolution field "responselike@1.0.0" is incompatible with requested version "responselike@^3.0.0"
warning Resolution field "responselike@1.0.0" is incompatible with requested version "responselike@^2.0.0"
└─ @glint/transform@0.9.4
✨  Done in 5.96s.
```

**Comment by csprocket777** [comment]
Better yet, here's everything I have relating to `glint`:

```javascript
yarn list --pattern "@glint"
yarn list v1.22.17
warning Resolution field "responselike@1.0.0" is incompatible with requested version "responselike@^3.0.0"
warning Resolution field "responselike@1.0.0" is incompatible with requested version "responselike@^2.0.0"
warning Resolution field "got@12.4.1" is incompatible with requested version "got@^10.5.2"
warning @semantic-release/npm > npm > node-gyp > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning Resolution field "got@12.4.1" is incompatible with requested version "got@^6.7.1"
warning Resolution field "responselike@1.0.0" is incompatible with requested version "responselike@^3.0.0"
warning Resolution field "responselike@1.0.0" is incompatible with requested version "responselike@^2.0.0"
├─ @glint/config@0.9.4
├─ @glint/core@0.9.4
├─ @glint/environment-ember-loose@0.9.4
├─ @glint/template@0.9.4
└─ @glint/transform@0.9.4
✨  Done in 5.59s.
```

**Comment by csprocket777** [comment]
For anyone (including my future-self) running into this, this was indeed a corruption of my local npm installation.

#### Resolution steps:
1. remove yarn
2. clear yarn files from $HOME directory
3. Use NVM to swap to another version of node
4. Use NVM to uninstall version of node being used previously
5. Reinstall node using NVM
6. Reinstall Glint globally

**Comment by dfreeman** [comment]
For future reference in case you or anyone else ever runs into a similar issue in the future: I think `yarn cache clean` would likely resolve problems like this without having to completely uninstall and reinstall Node and Yarn
