### ISSUE TITLE
VS Code Plugin Compatibility issue with Glimmer Templates Syntax for VS Code

### ISSUE THREAD

**Issue by csprocket777** [typed-ember/glint#407]
**OS:** macOS Monterey 12.5.1
**Editor:** VSCode 1.71.0
**Plugins:**
- Glint v0.9.1
- Glimmer Templates Syntax for VS Code v1.0.7

Context
-------------------
I have an ember-cli-typescript project that is consuming a glint enabled addon.

Expected
-------------------
When trying to use the addon, I'm looking for completion suggestions from the Glint plugin (ex: `<my-component @[...expect completion suggestions here]></my-component>`).

What's happening
-------------------
Instead I'm getting suggestions from history and other plugins but nothing from Glint.

Disabling the Glimmer Templates Syntax plugin allows glint to return completion suggestions.

Related
------------------
I also opened an issue in the repo of `Glimmer Templates Syntax for VS Code`: [issue](https://github.com/lifeart/vsc-ember-syntax/issues/27)

**Comment by chriskrycho** [comment]
Thanks for reporting this. It's *extremely* unclear to me why this would be happening, but I appreciate the report!

**Comment by chriskrycho** [comment]
After doing a little poking, I *strongly* suspect this is because of a bad interaction between the language server supplied by vsc-ember-syntax and the Glint language server. I don't know whose "fault" that is yet, but it would definitely be preferable from my POV if vsc-ember-syntax focused on syntax highlighting and had a separate package to supply the other HBS functionality it supplies (which is fairly minimal; it no doubt made sense to include initially!).

**Comment by dfreeman** [comment]
I can confirm that Glint is still receiving the completion request and responding correctly to it. My best guess is that `Glimmer Templates Syntax for VS Code` is doing something to cause those suggestions to be ignored or preempted in the UI.

It may be that it's changing the token structure somehow such that it doesn't the editor doesn't think any of our results match the prefix there? Regardless, I don't _think_ there's anything we're likely to be able to do from this end.

<img width="367" alt="image" src="https://user-images.githubusercontent.com/108688/196752480-be942253-8279-4e30-bd08-57c885d9cb75.png">

```js
[Trace - 6:39:57 PM] Sending request 'textDocument/completion - (10)'.
Params: {
    "textDocument": {
        "uri": "file:///Users/dfreeman/code/glint/test-packages/ts-ember-app/app/components/ember-component.hbs"
    },
    "position": {
        "line": 9,
        "character": 7
    },
    "context": {
        "triggerKind": 1
    }
}


[Trace - 6:39:57 PM] Received response 'textDocument/completion - (10)' in 6ms.
Result: [
    {
        "label": "hasDefault",
        "kind": 5,
        "data": {
            "uri": "file:///Users/dfreeman/code/glint/test-packages/ts-ember-app/app/components/ember-component.hbs",
            "transformedFileName": "/Users/dfreeman/code/glint/test-packages/ts-ember-app/app/components/ember-component.ts",
            "transformedOffset": 1562
        }
    },
    {
        "label": "optional",
        "kind": 5,
        "data": {
            "uri": "file:///Users/dfreeman/code/glint/test-packages/ts-ember-app/app/components/ember-component.hbs",
            "transformedFileName": "/Users/dfreeman/code/glint/test-packages/ts-ember-app/app/components/ember-component.ts",
            "transformedOffset": 1562
        }
    },
    {
        "label": "required",
        "kind": 5,
        "data": {
            "uri": "file:///Users/dfreeman/code/glint/test-packages/ts-ember-app/app/components/ember-component.hbs",
            "transformedFileName": "/Users/dfreeman/code/glint/test-packages/ts-ember-app/app/components/ember-component.ts",
            "transformedOffset": 1562
        }
    }
]
```

**Comment by lifeart** [comment]
Really strange, especially for `hbs` case, may be related to [this](https://github.com/lifeart/vsc-ember-syntax/blob/master/src/index.ts), logic, it's calling https://github.com/lifeart/typescript-hbs-plugin and it's getting completions from here https://github.com/lifeart/typescript-hbs-plugin/blob/main/src/html-template-language-service.ts#L83

**Comment by dfreeman** [comment]
> seems like vscode issue, because it's should collect all completions from extensions, instead of picking..

At least in the general case, I know Code does the right thing, because when you have the built-in TS tooling and Glint both active in the same project, you'll see completions from both of them intermingled.
