### ISSUE TITLE
support helper and modifier helpers

### ISSUE THREAD

**Issue by patricklx** [typed-ember/glint#410]
using `{{#let (helper ...)}...`  or `{{#let (modifier ...)}}` does not work

**Comment by chriskrycho** [comment]
Hi @patricklx, thanks for filing. Can you elaborate a bit?

- What versions of the Glint packages do you have?
- What is your `glint` config?
- What is the actual error you are seeing?

**Comment by patricklx** [comment]
sure:
* version: 0.9.3
* glint config: ember-loose  env, nothing else
* the actual error is: 
when I use `{{#let (helper "my-helper" as |myhelper|)}{{/helper}}` then the resolved type of myhelper is `any`

**Comment by patricklx** [comment]
btw, i already fixed it myself with this
```
declare module '@glint/environment-ember-loose/registry' {
  type helper = DirectInvokable<{
    <T extends keyof Registry>(args: EmptyObject, value: T): T extends keyof Registry ? Registry[T] : never
  }>;
  export default interface Registry {
    helper: helper;
    modifier: helper;
  }
}

```
