### ISSUE TITLE
Translated TypeScript of standalone templates fails to compile under --isolatedModules

### ISSUE THREAD

**Issue by bwbuchanan** [typed-ember/glint#459]
In a project that uses isolatedModules in its tsconfig.json, glint's translated TypeScript will fail to compile for some standalone templates ~~that don't use any components~~:

```
app/templates/error.ts:1:1 - error TS1208: 'error.ts' cannot be compiled under '--isolatedModules'
because it is considered a global script file. Add an import, export, or an empty 'export {}'
statement to make it a module.
```

The fix looks like it should be as simple as adding a dummy export to the generated TypeScript code.

**Comment by bwbuchanan** [comment]
Looks like something odd is going on here. The intermediate representation is not actually being generated for this template, so far as I can tell. `app/templates/error.ts` does not get created in GLINT_DEBUG and there's only a blank entry for it in the DocumentCache.

**Comment by dfreeman** [comment]
> The fix looks like it should be as simple as adding a dummy export to the generated TypeScript code.

I _think_ that should be as straightforward as updating this: https://github.com/typed-ember/glint/blob/1a83218cf0ac79759c32da47ea1d63360bcdef62/packages/core/src/common/transform-manager.ts#L375

> I think there's another bug in here, however, in that for excluded templates we're producing a blank TypeScript file instead of excluding it from the build entirely.

The contract of `include`/`exclude` is nebulous at best, but it's not obvious to me that it's a bug to represent excluded templates with an empty placeholder internally.

Either way, I've been begging the community for a while now to stop using `include`/`exclude` and switch to `@glint-nocheck`, updating every mention I can find in the docs and even building [a script](https://github.com/typed-ember/glint/tree/main/packages/scripts#auto-glint-nocheck) to automate that process, but it still seems to be what people reach for. If you know of resources out there that are still guiding folks to use `exclude` config, can you point me at them? 😅

**Comment by bwbuchanan** [comment]
Regarding `exclude`, I found it here: https://typed-ember.gitbook.io/glint/using-glint/_index

I probably skimmed right past the info box due to [banner blindness](https://en.wikipedia.org/wiki/Banner_blindness) and went straight to the example code.

**Comment by dfreeman** [comment]
I went to put a fix in place for this, but I wasn't able to reproduce the problem to ensure that my fix actually worked. Can you share a minimal reproduction?

**Comment by cafreeman** [comment]
@dfreeman fwiw i'm seeing this in the dummy app of an ember addon (specifically the `error.hbs` file, similar to OP), but *not* in a newly-generated ember app.

**Comment by dfreeman** [comment]
@cafreeman Thanks, it's helpful to know it's definitely not a one-off issue. I'm still stuck until I can actually see it in action and verify that I'm fixing it, though 🙂 

To confirm:
 - the newly-generated app you tested with has a template with no backing `.js`/`.ts` module in it somewhere?
 - are the app and the addon on the same TS version?
 - what differences are there in the `compilerOptions` between the app and the addon?

**Comment by bwbuchanan** [comment]
Reproduction: https://github.com/bwbuchanan/glint-459
