### ISSUE TITLE
Model not provided to error substate templates

### ISSUE THREAD

**Issue by bwbuchanan** [typed-ember/glint#460]
As per [the Ember guides](https://guides.emberjs.com/release/routing/loading-and-error-substates/), the thrown exception of promise rejection reason should be provided as the `model`.

However, glint rejects these templates accessing `{{@model}}`:

```
app/templates/error.hbs:11:6 - error TS2339: Property 'model' does not exist on type 'EmptyObject'.

11   {{@model}}
        ~~~~~
```

**Comment by dfreeman** [comment]
In Glint, we always treat templates with no backing module as effectively having no args or `this` value. While it's possible to infer that `@model` is _probably_ a route error based on the directory structure and file name, my leaning is to say that's not something we want to try and special-case (particularly given that routing in Ember is a major topic of discussion for being reworked in the near-ish future).

Instead, I'd suggest implementing a backing controller or route class (both of which the guides say you can optionally do for substate routes) that can provide appropriate type information for the templates, similar to [the recommendation we make for template-only components](https://typed-ember.gitbook.io/glint/using-glint/ember/template-only-components).

**Comment by bwbuchanan** [comment]
I'm fine with this approach.

This is something likely to trip up many people just trying to introduce glint to their existing app, so I think the resolution here is to document this somewhere that people are likely to find it before/when they run into the error.

**Comment by dfreeman** [comment]
Curiously you're the first to hit this (or at least to report it) in the year-and-a-half or so that folks have been trying out Glint, but I agree that it should be captured in the docs now that it's been flagged. I think a note about substate routes on [the Routes and Controllers](https://typed-ember.gitbook.io/glint/using-glint/ember/routes-and-controllers) would be useful.

**Comment by chriskrycho** [comment]
I suspect it's because use of the substate routes is relatively rare, and actually using the error as the model this way even rarer. I know people do it, but I have actually never seen it in the wild, and I'm not sure if *any* of the LinkedIn apps take advantage of that particular capability.
