### ISSUE TITLE
undefined buildOptions taking precedence over tsconfig compilerOptions entries

### ISSUE THREAD

**Issue by hmajoros** [typed-ember/glint#468]
## System Info
glint --version: 0.9.7
node --version: v16.14.0

## Problem
when running `glint --build`, I am seeing the following error when building a project containing project references:
```
Error: Debug Failure. project /Users/hmajoros/Job/voyager-web/tsconfig.json expected to have at least one output
    at Object.getFirstProjectOutput (/Users/hmajoros/Job/voyager-web/node_modules/typescript/lib/typescript.js:110333:25)
    at updateOutputTimestamps (/Users/hmajoros/Job/voyager-web/node_modules/typescript/lib/typescript.js:125327:38)
    at Object.done (/Users/hmajoros/Job/voyager-web/node_modules/typescript/lib/typescript.js:124629:21)
    at build (/Users/hmajoros/Job/voyager-web/node_modules/typescript/lib/typescript.js:125406:32)
    at Object.build (/Users/hmajoros/Job/voyager-web/node_modules/typescript/lib/typescript.js:125599:101)
    at performBuild (/Users/hmajoros/Job/voyager-web/node_modules/@glint/core/lib/cli/perform-build.js:17:69)
    at Object.<anonymous> (/Users/hmajoros/Job/voyager-web/node_modules/@glint/core/lib/cli/index.js:97:42)
```

after a bit of debugging, it appears the issue is that glint is setting `buildOptions.incremental` to `undefined`, since `argv.incremental` is undefined.
https://github.com/typed-ember/glint/blob/main/packages/core/src/cli/index.ts#L84

the downstream effects are that in the typescript compiler, `hasProperty(buildOptions, 'incremental')` is true, which overrides the `compilerOptions.incremental` field with `undefined`.
https://github.com/microsoft/TypeScript/blob/00dc0b6674eef3fbb3abb86f9d71705b11134446/src/compiler/tsbuildPublic.ts#L335

this then causes our program to error out, because the top level project is not `composite` or `incremental`:
https://github.com/microsoft/TypeScript/blob/00dc0b6674eef3fbb3abb86f9d71705b11134446/src/compiler/emitter.ts#L502

and therefore we cannot generate any output `buildInfo`:
https://github.com/microsoft/TypeScript/blob/00dc0b6674eef3fbb3abb86f9d71705b11134446/src/compiler/emitter.ts#L722

## Possible Solution
modify the following code to only set `incremental` in buildOptions if it was passed as a command-line arg.
https://github.com/typed-ember/glint/blob/main/packages/core/src/cli/index.ts#L84

```typescript
  let buildOptions: TS.BuildOptions = {
    clean: argv.clean,
    force: argv.force,
    dry: argv.dry,
  };
  if ('incremental' in argv) {
    buildOptions.incremental = argv.incremental;
  }
```

**Comment by hmajoros** [comment]
@dfreeman this is pretty similar to your PR here: https://github.com/typed-ember/glint/pull/428.

happy to put up a PR if you're cool with this solution

**Comment by dfreeman** [comment]
Yep, well spotted—it's exactly the same bug, I just didn't catch that we were setting that flag differently in `build` mode. I think the solution you proposed is exactly right 👍

**Comment by chriskrycho** [comment]
Ah, good sleuthing. (And my mistake in the original wiring!)
