### ISSUE TITLE
Test performance: reuse project setups?

### ISSUE THREAD

**Issue by chriskrycho** [typed-ember/glint#471]
In a number of the `--build` and `--incremental` tests, we currently re-create the entire project setup from scratch and then tear it down before and after every single test. We could probably skip a lot of that by doing `before` and `after` instead of `beforeEach` and `afterEach` for tests which share their setups, while still have some kind of `afterEach` cleanup for the bits we generate along the way. This should shave at least *some* time off of those incredibly and annoyingly long test runs.

**Comment by dfreeman** [comment]
I stuck some `performance.now()` measurements in the `beforeEach`/`afterEach` blocks and then ran the "simple `--build --watch`" tests:

```
stdout | __tests__/cli/build-watch.test.ts > CLI: watched build mode typechecking > simple projects using `--build --watch > passes a valid basic project
passes a valid basic project [ 2.4674553871154785, 3.93450927734375 ]

stdout | __tests__/cli/build-watch.test.ts > CLI: watched build mode typechecking > simple projects using `--build --watch > reports diagnostics for a template syntax error
reports diagnostics for a template syntax error [ 1.2247447967529297, 2.9417600631713867 ]

stdout | __tests__/cli/build-watch.test.ts > CLI: watched build mode typechecking > simple projects using `--build --watch > reports diagnostics for a template type error
reports diagnostics for a template type error [ 1.76670503616333, 2.7261571884155273 ]

stdout | __tests__/cli/build-watch.test.ts > CLI: watched build mode typechecking > simple projects using `--build --watch > reports on errors introduced and cleared during the watch
reports on errors introduced and cleared during the watch [ 1.2449560165405273, 3.5986580848693848 ]

 ✓ __tests__/cli/build-watch.test.ts (11) 14883ms
```

The 4 tests took a total of 14.9s to run, and of that each spent 4-6ms combined on setup and teardown, which accounts for a total of around 0.1% of the total runtime. Maybe there are some other advantages we can squeeze out of sharing test setup, but "just" cutting down on the setup and teardown times by themselves doesn't look like it will make much of a dent.

**Comment by chriskrycho** [comment]
Thanks for checking! It sort of makes sense given what we know about the overhead/time of just starting up `tsc` and the extra cost imposed by parsing all the templates for Glint that setup and teardown are not the major contributors. Would have been nice if it were a win but now we know.
