### ISSUE TITLE
as typescript plugin ?

### ISSUE THREAD

**Issue by patricklx** [typed-ember/glint#477]
Hi, 
I recently found this: https://github.com/mrmckeb/typescript-plugin-css-modules 
I wonder if it's possible to have glint as a plugin for typescript instead? Plugin do not work when compiling, but for language server. I'm not sure if its possible to obtain completions and annotations for hbs then.

But if yes, then would allow to keep the default ide integration with typescript and only would need customization for hbs files ide integration. And gts/gjs or template-imports with hbs tag would just work.

**Comment by dfreeman** [comment]
The Glint language server actually began its life as a tsserver plugin (you can still see it in the git history if you look back far enough), but those plugins are pretty limited in terms of what they can cleanly change about the processing of files, and in the end we decided it wasn't a feasible approach for the things we wanted Glint to be able to do.

From [the TS wiki](https://github.com/microsoft/TypeScript/wiki/Writing-a-Language-Service-Plugin#whats-a-language-service-plugin):

> Examples of things language plugins cannot do:
>
> - Add new custom syntax to TypeScript
> - Change how the compiler emits JavaScript
> - Customize the type system to change what is or isn't an error when running tsc

Glint's entire purpose is to do two of those three things! 🙂
