### ISSUE TITLE
Document how to do generic types?

### ISSUE THREAD

**Issue by simonihmig** [typed-ember/glint#529]
Template-only components cannot be generic types themselves AFAIU, same goes for function-based modifiers, right?

For function-based helpers I am not so sure, I think the same for the "classic" syntax, but with plain-functions-as-helpers that should work?

Question: should we document this somehow, and provide "officially endorsed" workarounds? (which is to convert to classes?)

**Comment by dfreeman** [comment]
I believe we currently have a note about this on the [template-only components page](https://typed-ember.gitbook.io/glint/using-glint/ember/template-only-components)
