### ISSUE TITLE
feature: outline provide in VS Code

### ISSUE THREAD

**Issue by chriskrycho** [typed-ember/glint#538]
Just a nice-to-have, but a really useful one: we should provide an outline view in the VS Code extension.

**Comment by dfreeman** [comment]
Totally not obvious from the user's perspective, but this is actually a dupe of #271, since in-document symbol navigation is powered off the same LSP call that produces the document outline.

**Comment by chriskrycho** [comment]
Oh, neat. Closing this in favor of that!

**Comment by donatocayurin** [comment]
❤️🙏

**Comment by donatocayurin** [comment]
❤️🙏
