### ISSUE TITLE
support `additionalGlobals` in `environment-ember-template-imports`

### ISSUE THREAD

**Issue by hmajoros** [typed-ember/glint#543]
building off the work here https://github.com/typed-ember/glint/pull/399, we should support `additionalGlobals` as a config option for the `template-imports` environment.

**Comment by hmajoros** [comment]
@chriskrycho @dfreeman it actually looks like this is already available via the `additionalSpecialForms` option in the template-imports environment. I think we can close this out as "done" actually

**Comment by dfreeman** [comment]
`additionalSpecialForms` does something slightly different—it _can_ introduce globals, but in doing so you're telling Glint that those globals should be treated as one of a special known set of syntactic transformations directly into equivalent TypeScript. See https://github.com/typed-ember/glint/pull/453 for more context on that.
