### ISSUE TITLE
Typing argument as union of string | Component leads to glint error

### ISSUE THREAD

**Issue by danieljust** [typed-ember/glint#546]
Hi Team, could you please assist me with understanding :) 

I've composed an example repo: https://github.com/danieljust/glint-question-1

**What I do:** 
I try to pass an argument into component, this argument can be a string or component.

I noticed that if I try to type argument as component only, then everything works just fine. 
But if I use union `string | SomeComponent` Glint starts screaming at me. 

```typescript 
interface ComponentASignature {
  Element: HTMLDivElement;
  Args: {
    onlyComponent: typeof ComponentAsArgument; 
    componentUnionString: string | typeof ComponentAsArgument; 
  }
}
```

This actually doesn't work if I use union with any other type mentioned in 
```typescript
export type ContentValue =
  | string
  | number
  | boolean
  | null
  | undefined
  | void
  | SafeString
  | Node
  | ArglessCurlyComponent;
```
**What I see:** 
in attached repo in app/components/main-component.hbs you may see the following error: 
<img width="938" alt="Screen Shot 2023-03-17 at 7 14 31 PM" src="https://user-images.githubusercontent.com/11667002/225947209-973bb322-3ec0-4252-9dc2-21718a9e310b.png">

**Comment by dfreeman** [comment]
This is a limitation of how TypeScript handles overloaded function signatures: a function with a signature that accepts `A` and a signature that accepts `B` doesn't automatically accept `A | B`.

See this playground for a (very simplified) example: https://www.typescriptlang.org/play?#code/C4TwDgpgBAwg9gWzHAdhFwoF4oG8oCWAggkfEqusAFxTABOArtAL4DcAUBwCYQDGAGwCG9aADNGKPsAKooolL3rlkaDAAoUQhBFoBnBgRQBzAJS0AbnALdOvQSPGTpslPPRKVlDX0SqqtF5qwOZQVjacXPbColC+KAZQABIQAgJwgX7ewHb8MdDxiQAWqekAQiAActoQAPL0AGpCAsz6hiZQAD504BBwYsmlcJEKnlnB6gDkJWlwk6acoxDK41TqKbMLHEsrFBMz5VU19U0tEAtAA
