### ISSUE TITLE
`{{modifier}}` fails when pre-binding multiple positional arguments

### ISSUE THREAD

**Issue by vstefanovic97** [typed-ember/glint#559]
When trying to work with modifiers I found a couple of things that were not working as expected.
Created a fork and added components for reproduction:

https://github.com/typed-ember/glint/compare/main...vstefanovic97:glint:main

All of the code is valid ember code but all three examples get TS errors

**Comment by dfreeman** [comment]
Your first example (`as |snake-case-modifier|`) is working as expected. As the error says, Glint requires block parameters to be valid TS identifiers, though object property names can be snake-case.

The second and third example are both the same issue, which we've already got a bugfix in flight for.
