### ISSUE TITLE
Autocompletion of args in vscode is incorrect

### ISSUE THREAD

**Issue by bakerac4** [typed-ember/glint#566]
When I try to use a `gts` file, it seems like if there are other autocompletions it wont show the autocompletions for my component args. However when I get to a more specific argument (past those other autocompletions) it will show, and then if you delete characters to get it back to where it wasn't showing before it will still show (and not show the other autocompletions).

I suspect this could be a env issue with my vscode but would love for someone to confirm this for me.

Here is what I am talking about with pictures.
<img width="548" alt="Screen Shot 2023-04-28 at 9 10 30 AM" src="https://user-images.githubusercontent.com/9952936/235159095-fe48a9c2-7a80-433a-a237-2c2367ae7858.png">

<img width="605" alt="Screen Shot 2023-04-28 at 9 10 36 AM" src="https://user-images.githubusercontent.com/9952936/235159113-482aebe7-cb00-4552-b8e7-cae8d221f86a.png">

<img width="888" alt="Screen Shot 2023-04-28 at 9 10 43 AM" src="https://user-images.githubusercontent.com/9952936/235159124-5b2fcafa-0bcc-4470-a31f-1e0ab9982f27.png">

**Comment by dfreeman** [comment]
And just to confirm, this is _only_ in `.gts` files—you don't see this behavior in `.hbs` ones?

**Comment by bakerac4** [comment]
Thats correct. I just made a test
<img width="788" alt="Screen Shot 2023-04-28 at 9 27 50 AM" src="https://user-images.githubusercontent.com/9952936/235160497-3d73eff5-1c05-43ea-8464-3fa0b761045d.png">
 file with a normal template. Here is an attached picture.
