### ISSUE TITLE
issue in combination with glint-template-types

### ISSUE THREAD

**Issue by patricklx** [typed-ember/glint#594]
I know exclude/include has been removed as of 1.0 and node_modules is also included to have same behaviour as typescript.
But I think it should not process the .hbs files in the node_modules.
Its a problem when using ember-basic-dropdown with glint-template-types

**Comment by patricklx** [comment]
okay, it was actually this issue: https://github.com/cibernox/ember-power-select/pull/1577
but is there any advantage in type checking hbs files in node_modules? especially if its a companion template

**Comment by dfreeman** [comment]
Just like TypeScript, we're not going to change behavior based on whether the arbitrary string `node_modules` appears in a file's path or not. This has been discussed in detail in several places both on GitHub and Discord, e.g. [here](https://github.com/typed-ember/glint/issues/507#issuecomment-1371088313).
