### ISSUE TITLE
in loose mode, hovering over a component should should the comment block on the actual component, especially if there isn't a comment block on the registrys entry

### ISSUE THREAD

**Issue by NullVoxPopuli** [typed-ember/glint#622]
yeah?

right now the only hove block shown in loose mode is that which is on the registry entry -- which doesn't carry over to gjs/gts.

defining the comment on the actual component does carry over to gjs/gts.

**Comment by dfreeman** [comment]
This isn't something we're going to try and fix; it's a fundamental limitation of loose mode. See https://www.youtube.com/watch?v=MLpP8D3cY7M&list=PLelyiwKWHHApkoeXQjwKPHPAHgKXZyl3t&index=2&t=3098s for details.

**Comment by NullVoxPopuli** [comment]
Gotchya, so the solution is to move things to not loose mode.

_perfect_ muahaha
