### ISSUE TITLE
VSCode release

### ISSUE THREAD

**Issue by chrisvdp** [typed-ember/glint#631]
I noticed that the current version of glint published in the vscode marketplace is 1.0.3 while the current version here is in the 1.2.0 range.

https://marketplace.visualstudio.com/items?itemName=typed-ember.glint-vscode

**Comment by dfreeman** [comment]
There have been no changes to the Code extension since 1.0.3, and it uses your local copy of `@glint/core`, so there's been no reason to do a release to the Code Marketplace.

We should probably put a note in the extension's README to that effect.
