### ISSUE TITLE
@glint/environment-ember-template-imports is incompatible with ember-template-imports 4.0.0

### ISSUE THREAD

**Issue by rohitpaulk** [typed-ember/glint#665]
The current package.json requires ember-template-imports to be 3.x.x: https://github.com/typed-ember/glint/blob/cd2d5775ba125f75c6d79da398a65773ccf071eb/packages/environment-ember-template-imports/package.json#L30

4.x release: https://github.com/ember-template-imports/ember-template-imports/releases/tag/v4.0.0

**Comment by NullVoxPopuli** [comment]
In the latest Glint release, https://github.com/typed-ember/glint/releases/tag/1.2.2

This PR should have been included: https://github.com/typed-ember/glint/pull/660

Which should allow apps to use `ember-template-imports@v4`
