### ISSUE TITLE
Unknown name 'page-title'

### ISSUE THREAD

**Issue by gabrielflorit** [typed-ember/glint#691]
The {{page-title}} helper throws the following error:

```
Unknown name 'page-title'. If this isn't a typo, you may be missing a registry entry for this value; see the Template Registry page in the Glint documentation for more details. glint (7053) [1, 3]
    Element implicitly has an 'any' type because expression of type '"page-title"' can't be used to index type 'Globals'. 
        Property 'page-title' does not exist on type 'Globals'. 
```

I consulted the Template Registry page but there's no instructions on how to deal with "built-in" helpers like page-title.

Any advice here would be much appreciated!

**Comment by NullVoxPopuli** [comment]
Thanks for reporting!

However, https://github.com/ember-cli/ember-page-title/ isn't built in tho, you'll want to follow the Glint section of the readme there to get the loose-mode invocation into your template-registry.

https://github.com/ember-cli/ember-page-title/#typescript-and-glint
