### ISSUE TITLE
Parse error on `{{!` mustache comment in `.gts`

### ISSUE THREAD

**Issue by chancancode** [typed-ember/glint#706]
```gts
<template>
  {{!
    like this
  }}
</template>
```

```
Parse error on line 2:
...                  {{!                  
-----------------------^
Expecting 'OPEN_SEXPR', 'ID', 'STRING', 'NUMBER', 'BOOLEAN', 'UNDEFINED', 'NULL', 'DATA', got 'INVALID'glint
```

**Comment by chancancode** [comment]
@NullVoxPopuli you tried this on #655? I would think the problem is that Glint is using too old a version of `@glimmer/syntax`, not because of the stuff content-tag would fix

**Comment by chancancode** [comment]
I think prettier wants to format into this style out of the box so this is somewhat of a blocker in converting `.hbs` files with comments

**Comment by dfreeman** [comment]
We have examples of this parsing fine in general (e.g. [here](https://github.com/typed-ember/glint/blob/5b5a29452942f924aaeee60ac7f56fdc954c59a2/test-packages/ts-template-imports-app/src/Playground.gts#L34)), so this may need a more detailed reproduction

**Comment by chancancode** [comment]
Aha, you are right, it requires `\`` inside the comment, so @NullVoxPopuli is right that this is in fact #655 territories

```gts
export default class Foo {
  <template>{{! ` }}</template>
}
```
