### ISSUE TITLE
[volar] implicit dependency on vscode-languageserver-protocol leads to server boot errors

### ISSUE THREAD

**Issue by runspired** [typed-ember/glint#778]
`vscode-languageserver-protocol` is used by the language-server here:

https://github.com/typed-ember/glint/blob/e88e08e442389060ea255dab05de085721f4f51d/packages/core/src/volar/language-server.ts#L17

but is not specified here:

https://github.com/typed-ember/glint/blob/e88e08e442389060ea255dab05de085721f4f51d/packages/core/package.json#L33-L54

There may be other implicit deps but I didn't find them. I think the reason this has gone largely unnoticed is that 

In `1.5.0` this is brought by `vscode-languageserver` which may be why this has gone unnoticed.

**Comment by NullVoxPopuli** [comment]
:shakes fist at cloud: YAAARRRRRNNNN
