### ISSUE TITLE
Bug with Mixin usage

### ISSUE THREAD

**Issue by boris-petrov** [typed-ember/glint#81]
Check [this repo](https://github.com/boris-petrov/glint-issues) (actually [this](https://github.com/boris-petrov/glint-issues/commit/556fe399e1014e73746a24851a8095df50a56651) specific commit). It adds a mixin and a component that uses it.

Running `./node_modules/.bin/tsc --noEmit` leads to no errors. However, running `./node_modules/.bin/glint` causes:

```
app/components/test-component.ts:4:44 - error TS4020: 'extends' clause of exported class 'TestComponent' has or is using private name 'ICalendar'.

4 export default class TestComponent extends Component.extend(Calendar) {
                                             ~~~~~~~~~~~~~~~~~~~~~~~~~~

app/components/test-component.ts:4:44 - error TS4020: 'extends' clause of exported class 'TestComponent' has or is using private name 'ICalendar'.

4 export default class TestComponent extends Component.extend(Calendar) {
                                             ~~~~~~~~~~~~~~~~~~~~~~~~~~
```

There shouldn't be a difference here as there are is no HBS involved so `Glint` should behave exactly the same as `tsc`.

P.S. Exporting the `ICalendar` interface fixes the errors however I still believe this is a bug because of the discrepancy between the two type-checkers.

**Comment by dfreeman** [comment]
Usually those errors will only pop up with `--declaration`, because you wind up with an expression TypeScript doesn't know how to emit a type for. If you're seeing them from the `glint` CLI _without_ using `--declaration`, that's definitely a bug. Thanks for the report!
