### ISSUE TITLE
Cannot specify that a helper doesn't have mandatory positional parameters

### ISSUE THREAD

**Issue by boris-petrov** [typed-ember/glint#83]
[This commit](https://github.com/boris-petrov/glint-issues/commit/1d06bf0ef2544bf6ea9eb193572d6e5fd794bd3b) in my reproduction repo.

As you see, I've specified `PositionalArgs: [string | undefined]` which should mean that a positional argument is not mandatory. But `glint` complains:

```
app/components/test-component.hbs:1:1 - error TS2554: Expected 2 arguments, but got 1.

1 {{test-helper-1 foo="bar"}}
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by dfreeman** [comment]
> I've specified `PositionalArgs: [string | undefined]` which should mean that a positional argument is not mandatory

That's not what that means 🙂 

If you take a look at [this playground](https://www.typescriptlang.org/play?#code/C4TwDgpgBAsiCCAnA5gZygXigbVcRAlgHbJQA+UArkQCYQBmxENAugNwCwAUHQMYA2AQ0TR61XsAIB7IlAC2IAGLjJMgBQA6LcLQAuWAhSoAlPoBuUgjU5duC5UQnSiagOQALCP35TXxtlCBAPRBUICg5HZKKs5q1HSMRMz+UCHhkQ5O6smBObmpgLwbgKU7QA), specifying your args that way (for a regular function, not just for Glint) requires that a parameter be passed.

```ts
type MyArgs = [string | undefined];
declare function myFunction(...args: MyArgs): void;

myFunction('hello');   // ✅
myFunction(undefined); // ✅
myFunction();          // 💥
```

You probably want `PositionalArgs: [string?]` or `PositionalArgs: [string] | []` instead, depending on whether you want to allow explicitly passing `undefined` or not.

**Comment by boris-petrov** [comment]
@dfreeman - you're absolutely right, of course. `[string?]` must be new because when I wrote that code it wasn't. :smile: But `[string] | []` does work always, I should have thought. Thanks!
