### ISSUE TITLE
Built-in components have no declared primary elements

### ISSUE THREAD

**Issue by boris-petrov** [typed-ember/glint#85]
[This commit](https://github.com/boris-petrov/glint-issues/commit/b4451f730f3451b56bad26512a9abc6af75482ae) in my reproduction repo.

The built-in `Input` component supports passing both `value` and `@value` (as well as a number of other similar properties). Glint doesn't - when using a property without a `@`, the following errors is emitted:

```
app/components/test-component.hbs:3:1 - error TS2344: Type 'null' does not satisfy the constraint 'Element'.

3 <Input value="asd" />
  ~~~~~~~~~~~~~~~~~~~~~
```

**Comment by dfreeman** [comment]
Ah, the built-in components missed the boat when we landed support for typechecking components' `...attributes`. We need to update `<LinkTo>` and `<Textarea>` as well, most likely. Thanks for the report!
