### ISSUE TITLE
Type 'MyComponentArgs' has no properties in common with type 'ComponentSignature'.

### ISSUE THREAD

**Issue by wagenet** [typed-ember/glint#88]
```
app/components/welcome-bar.ts:16:51 - error TS2559: Type 'WelcomeBarArgs' has no properties in common with type 'ComponentSignature'.

16 export default class WelcomeBar extends Component<WelcomeBarArgs> {
```

**Comment by chriskrycho** [comment]
What is the type of `WelcomeBarArgs`? I expect it's the classic `Args` definition, something like this?

```ts
interface WelcomeBarArgs {
  name: string;
}
```

Assuming so, it needs to be updated to the new signature:

```ts
interface WelcomeBarSignature {
  Args: { 
    name: string;
  }
}
```

This is what allows us to support handling `Element`, `Yields`, etc. in a forward-compatible and all-of-them-are-optional way. See [**Component Signatures**](https://github.com/typed-ember/glint#component-signatures) for details.

**Comment by wagenet** [comment]
I think this may have just been because I didn't add it to the registry.

**Comment by wagenet** [comment]
I'll close if that turns out to be the case.
